language: generic
dist: xenial

stages:
- name: danger
  if: type = pull_request
- name: deploy
  if: tag IS present

os: osx

osx_image: xcode11.5

jobs:
  include:
  - stage: deploy
    script: bash .deploy-docs.sh
  - stage: danger
    script: swift run danger-swift ci
    install:
    - python3 scripts/include_dev_dependencies.py
    - npm install -g danger
    - swift build
    after_success: python3 scripts/remove_dev_dependencies.py

cache:
  directories:
  - .build
  - ~/.danger-swift