os:
- osx
- linux
language: generic
sudo: false
dist: trusty
osx_image:
- xcode9
- xcode10
env:
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.0.2
- SWIFT_VERSION=4.0.3
- SWIFT_VERSION=4.1
- SWIFT_VERSION=4.1.1
- SWIFT_VERSION=4.1.2
- SWIFT_VERSION=4.1.3
- SWIFT_VERSION=4.2
matrix:
  exclude:
  - osx_image: xcode9
    env: SWIFT_VERSION=4.2
  - os: linux
    osx_image: xcode9
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
- swift test
before_deploy:
- jazzy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: docs/
  email: docbot@travis-ci.com
  name: Documentation Bot