os:
- osx
- linux
language: generic
sudo: false
dist: trusty
osx_image:
- xcode9
- xcode10
env:
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.0.2
- SWIFT_VERSION=4.0.3
- SWIFT_VERSION=4.1
- SWIFT_VERSION=4.1.1
- SWIFT_VERSION=4.1.2
- SWIFT_VERSION=4.1.3
- SWIFT_VERSION=4.2
matrix:
  exclude:
  - osx_image: xcode9
    env: SWIFT_VERSION=4.2
  - os: linux
    osx_image: xcode9
  include:
  - osx_image: xcode10
    os: osx
    env:
    - SWIFT_VERSION=4.2
    - DEPLOY=TRUE
install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
- if $DEPLOY; gem install jazzy; fi
script:
- swift test
deploy:
  skip_cleanup: true
  provider: script
  script: bash .deploy-docs.sh
  on:
    branch: development
    condition: $DEPLOY
  all_branches: true
