language: generic
sudo: false
dist: trusty


os:
- osx
- linux

osx_image:
- xcode9
- xcode10

env:
- SWIFT_VERSION=4.0
- SWIFT_VERSION=4.0.2
- SWIFT_VERSION=4.0.3
- SWIFT_VERSION=4.1
- SWIFT_VERSION=4.1.1
- SWIFT_VERSION=4.1.2
- SWIFT_VERSION=4.1.3

matrix:
  exclude:
  - os: linux
    osx_image: xcode9

jobs:
  include:
  - osx_image: xcode10
    os: linux
    env: SWIFT_VERSION=4.2
    script: swift test
  - stage: test
    if: branch != master
    osx_image: xcode10
    os: osx
    env: SWIFT_VERSION=4.2
    script: swift test
  - stage: deploy
    if: branch = master
    osx_image: xcode10
    os: osx
    env: SWIFT_VERSION=4.2
    script: bash .deploy-docs.sh


install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
- swift test