language: generic
sudo: false
dist: trusty

stages:
- test
- name: danger
  if: type = pull_request
- name: deploy
  if: branch = master AND type = push

os:
- osx
- linux

osx_image: xcode10

env:
- SWIFT_VERSION=4.2.4
- SWIFT_VERSION=5.0.1

jobs:
  include:
  - osx_image: xcode10.2
    os: linux
    env: SWIFT_VERSION=5.0.1
    script: swift test
  - stage: test
    if: branch != master OR type = pull_request
    osx_image: xcode10.2
    os: osx
    env: SWIFT_VERSION=5.0.1
    script: swift test
  - stage: deploy
    if: branch = master AND type = push
    osx_image: xcode10.2
    os: osx
    env: SWIFT_VERSION=5.0.1
    script: bash .deploy-docs.sh
  - stage: danger
    script: swift run danger-swift ci
    install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
    - npm install -g danger
    - swift build

cache:
  directories:
  - .build
  - ~/.danger-swift

install:
- eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

script:
- swift test
